//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Practical1Entities1 : DbContext
    {
        public Practical1Entities1()
            : base("name=Practical1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<RaceStat> RaceStats { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<RaceName> RaceNames { get; set; }
        public virtual DbSet<RaceResult> RaceResults { get; set; }
    }
}
