//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceStat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RaceStat()
        {
            this.RaceNames = new HashSet<RaceName>();
        }
    
        public string RaceName { get; set; }
        public Nullable<decimal> TotalRun { get; set; }
        public Nullable<decimal> CompRun { get; set; }
        public Nullable<decimal> NoFemale { get; set; }
        public Nullable<decimal> NoMale { get; set; }
        public string MWname_first { get; set; }
        public string MWname_last { get; set; }
        public Nullable<decimal> MW_age { get; set; }
        public string FWname_first { get; set; }
        public string FWname_last { get; set; }
        public Nullable<decimal> FW_age { get; set; }
        public string MMname_first { get; set; }
        public string MMname_last { get; set; }
        public Nullable<decimal> MM_age { get; set; }
        public string FMname_first { get; set; }
        public string FMname_last { get; set; }
        public Nullable<decimal> FM_age { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceName> RaceNames { get; set; }
    }
}
