//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceResult
    {
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string RaceName { get; set; }
        public Nullable<System.TimeSpan> TimeCompletd { get; set; }
    }
}
