//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceName
    {
        public string PPSno { get; set; }
        public string RaceName1 { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<System.TimeSpan> TimeCompletd { get; set; }
    
        public virtual Participant Participant { get; set; }
        public virtual RaceStat RaceStat { get; set; }
    }
}
